"""create composite unique constraint for insights table

Revision ID: 020582b76962
Revises: 381114f3a9df
Create Date: 2025-09-13 14:29:38.364625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020582b76962'
down_revision: Union[str, None] = '381114f3a9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_insights_dataset_id'), 'insights', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_dataset_id'), table_name='insights')
    # ### end Alembic commands ###
