"""adding default token_version value

Revision ID: 0a31e23f000c
Revises: 5b6c59cdfa3d
Create Date: 2025-08-08 14:56:38.623550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a31e23f000c'
down_revision: Union[str, None] = '5b6c59cdfa3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
