"""edit duration_days to be nullable

Revision ID: 0c868309bedd
Revises: 2a78b2f42cdf
Create Date: 2025-08-07 13:54:06.309070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c868309bedd'
down_revision: Union[str, None] = '2a78b2f42cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'duration_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'subscriptions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.alter_column('subscription_plans', 'duration_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
