"""add delete cascade for insight_reviews

Revision ID: 1548743e4c83
Revises: df310a96dc82
Create Date: 2025-10-02 15:37:13.957762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1548743e4c83'
down_revision: Union[str, None] = 'df310a96dc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('insight_reviews_reviews_id_fkey', 'insight_reviews', type_='foreignkey')
    op.drop_constraint('insight_reviews_insight_id_fkey', 'insight_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'insight_reviews', 'reviews', ['reviews_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'insight_reviews', 'insights', ['insight_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insight_reviews', type_='foreignkey')
    op.drop_constraint(None, 'insight_reviews', type_='foreignkey')
    op.create_foreign_key('insight_reviews_insight_id_fkey', 'insight_reviews', 'insights', ['insight_id'], ['id'])
    op.create_foreign_key('insight_reviews_reviews_id_fkey', 'insight_reviews', 'reviews', ['reviews_id'], ['id'])
    # ### end Alembic commands ###
