"""first migration

Revision ID: 2a78b2f42cdf
Revises: 
Create Date: 2025-08-07 11:06:16.415231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a78b2f42cdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #starting creating enums

    # op.execute("CREATE TYPE user_role_enum AS ENUM ('user', 'admin', 'superadmin')")
    # op.execute("CREATE TYPE user_auth_provider_enum AS ENUM ('google', 'local')")
    # op.execute("CREATE TYPE user_status_enum AS ENUM ('active', 'deactivated', 'deleted')")
    # op.execute("CREATE TYPE payment_method_enum AS ENUM ('local')")
    # op.execute("CREATE TYPE payment_status_enum AS ENUM ('success', 'failed', 'invalid', 'pending')")
    # op.execute("CREATE TYPE tier_name_enum AS ENUM ('Base', 'Mid', 'Pro')")
    # op.execute("CREATE TYPE scrape_usage_status_enum AS ENUM ('pending', 'success', 'failed', 'nores')")
    # op.execute("CREATE TYPE scrape_usage_provider_enum AS ENUM ('apify')")
    # op.execute("CREATE TYPE billing_cycle_enum AS ENUM ('monthly', 'annually', 'free')")
    # op.execute("CREATE TYPE currency_enum AS ENUM ('usd', 'idr')")
    # op.execute("CREATE TYPE transaction_status_enum AS ENUM ('pending', 'paid', 'failed')")
    # op.execute("CREATE TYPE text_platform_enum AS ENUM ('gmaps')")
    # op.execute("CREATE TYPE text_sentiment_enum AS ENUM ('positive', 'negative', 'neutral')")
    # op.execute("CREATE TYPE text_language_enum AS ENUM ('ID', 'EN')")
    # op.execute("CREATE TYPE subscription_status_enum AS ENUM ('active', 'pending', 'expired', 'freeze', 'trial', 'canceled')")

    #ending creating enums
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_ref', sa.UUID(), nullable=True),
    sa.Column('method', postgresql.ENUM('local', name='payment_method_enum'), nullable=False),
    sa.Column('status', postgresql.ENUM('success', 'failed', 'invalid', 'pending', name='payment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=True)
    op.create_index(op.f('ix_payments_provider_ref'), 'payments', ['provider_ref'], unique=False)
    op.create_table('tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', postgresql.ENUM('Base', 'Mid', 'Pro', name='tier_name_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiers_id'), 'tiers', ['id'], unique=False)
    op.create_index(op.f('ix_tiers_name'), 'tiers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'admin', 'superadmin', name='user_role_enum'), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'deactivated', 'deleted', name='user_status_enum'), nullable=False),
    sa.Column('provider', postgresql.ENUM('google', 'local', name='user_auth_provider_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('scrape_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_scrape', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'success', 'failed', 'nores', name='scrape_usage_status_enum'), nullable=False),
    sa.Column('provider', postgresql.ENUM('apify', name='scrape_usage_provider_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_usages_id'), 'scrape_usages', ['id'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_cycle', postgresql.ENUM('monthly', 'annually', 'free', name='billing_cycle_enum'), nullable=False),
    sa.Column('currency', postgresql.ENUM('usd', 'idr', name='currency_enum'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=True)
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'failed', name='transaction_status_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=True)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_table('scraped_text',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('platform', postgresql.ENUM('gmaps', name='text_platform_enum'), nullable=False),
    sa.Column('sentiment', postgresql.ENUM('positive', 'negative', 'neutral', name='text_sentiment_enum'), nullable=True),
    sa.Column('language', postgresql.ENUM('ID', 'EN', name='text_language_enum'), nullable=False),
    sa.Column('scrape_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape_usages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_text_id'), 'scraped_text', ['id'], unique=True)
    op.create_index(op.f('ix_scraped_text_scrape_id'), 'scraped_text', ['scrape_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'pending', 'expired', 'freeze', 'trial', 'canceled', name='subscription_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transactions_id', sa.UUID(), nullable=False),
    sa.Column('plans_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plans_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['transactions_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('transactions_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_scraped_text_scrape_id'), table_name='scraped_text')
    op.drop_index(op.f('ix_scraped_text_id'), table_name='scraped_text')
    op.drop_table('scraped_text')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_scrape_usages_id'), table_name='scrape_usages')
    op.drop_table('scrape_usages')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tiers_name'), table_name='tiers')
    op.drop_index(op.f('ix_tiers_id'), table_name='tiers')
    op.drop_table('tiers')
    op.drop_index(op.f('ix_payments_provider_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
