"""change score columns in insights table

Revision ID: 381114f3a9df
Revises: d29cc056f565
Create Date: 2025-09-13 13:54:05.633875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381114f3a9df'
down_revision: Union[str, None] = 'd29cc056f565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('emerging_score', sa.DOUBLE_PRECISION(), nullable=False))
    op.drop_column('insights', 'frequent_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('frequent_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('insights', 'emerging_score')
    # ### end Alembic commands ###
