"""create the modified users table v1

Revision ID: 51333dbaeb8d
Revises: b735379e3491
Create Date: 2025-07-27 19:04:29.214478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51333dbaeb8d'
down_revision: Union[str, None] = 'b735379e3491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE user_tier_enum AS ENUM ('Base', 'Mid', 'Pro')")
    op.add_column('users', sa.Column('tier', sa.Enum('Base', 'Mid', 'Pro', name='user_tier_enum'), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('users', 'tier')
    op.execute("DROP TYPE user_tier_enum")
    # ### end Alembic commands ###
