"""change subscriptions plans code to nullable

Revision ID: 53f67d21aa9d
Revises: 9e25c023a46b
Create Date: 2025-08-14 17:09:26.525257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f67d21aa9d'
down_revision: Union[str, None] = '9e25c023a46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscription_plans_code', table_name='subscription_plans')
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.create_index('ix_subscription_plans_code', 'subscription_plans', ['code'], unique=True)
    # ### end Alembic commands ###
