"""add delete cascade at task rollback

Revision ID: 569542cf64d7
Revises: efdee5ad23ae
Create Date: 2025-09-15 14:02:33.196790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569542cf64d7'
down_revision: Union[str, None] = 'efdee5ad23ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reviews_provider_ref_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'data_source_log', ['provider_ref'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_provider_ref_fkey', 'reviews', 'data_source_log', ['provider_ref'], ['id'])
    # ### end Alembic commands ###
