"""add token_version to user table

Revision ID: 5b6c59cdfa3d
Revises: 0c868309bedd
Create Date: 2025-08-08 14:48:04.827833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6c59cdfa3d'
down_revision: Union[str, None] = '0c868309bedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=True))
    # op.execute('UPDATE users SET token_version = 1')
    op.alter_column('users', 'token_version', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
