"""add provider, password nullable

Revision ID: 90096d1cbe4d
Revises: 88d9b6835a04
Create Date: 2025-07-28 12:57:47.224417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90096d1cbe4d'
down_revision: Union[str, None] = '88d9b6835a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE user_auth_provider_enum AS ENUM ('google', 'local')")
    op.add_column('users', sa.Column('provider', sa.Enum('google', 'local', name='user_auth_provider_enum'), nullable=True))
    op.execute("UPDATE users SET provider='local'")
    op.alter_column('users', 'provider', nullable=False)
    op.alter_column('users', 'password', nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
