"""another init

Revision ID: c36665a1af39
Revises: 
Create Date: 2025-09-07 16:25:55.895076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c36665a1af39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', postgresql.ENUM('scrape', 'local', name='data_provider_enum'), nullable=False),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_log_id'), 'data_source_log', ['id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_ref', sa.UUID(), nullable=True),
    sa.Column('method', postgresql.ENUM('local', name='payment_method_enum'), nullable=False),
    sa.Column('status', postgresql.ENUM('success', 'failed', 'invalid', 'pending', name='payment_status_enum'), nullable=False),
    sa.Column('amount_charged', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=True)
    op.create_index(op.f('ix_payments_provider_ref'), 'payments', ['provider_ref'], unique=False)
    op.create_table('tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', postgresql.ENUM('Base', 'Mid', 'Pro', name='tier_name_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiers_id'), 'tiers', ['id'], unique=False)
    op.create_index(op.f('ix_tiers_name'), 'tiers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'admin', 'superadmin', name='user_role_enum'), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'deactivated', 'deleted', name='user_status_enum'), nullable=False),
    sa.Column('provider', postgresql.ENUM('google', 'local', name='user_auth_provider_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('is_empty', sa.Boolean(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'extracted', 'failed', name='dataset_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=True)
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_cycle', postgresql.ENUM('monthly', 'annually', 'free', name='billing_cycle_enum'), nullable=False),
    sa.Column('currency', postgresql.ENUM('usd', 'idr', name='currency_enum'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=False)
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'failed', name='transaction_status_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('plan_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=True)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('platform', postgresql.ENUM('gmaps', 'user', name='text_platform_enum'), nullable=False),
    sa.Column('language', postgresql.ENUM('ID', 'EN', name='text_language_enum'), nullable=False),
    sa.Column('sentiment', postgresql.ENUM('positive', 'negative', 'neutral', name='text_predicted_sentiment_enum'), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('provider_ref', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['provider_ref'], ['data_source_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_dataset_id'), 'reviews', ['dataset_id'], unique=True)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'pending', 'expired', 'freeze', 'trial', 'canceled', name='subscription_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transactions_id', sa.UUID(), nullable=False),
    sa.Column('plans_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plans_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['transactions_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('transactions_id')
    )
    op.create_table('insight_reviews',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('reviews_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['reviews_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('insight_id', 'reviews_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insight_reviews')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_dataset_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tiers_name'), table_name='tiers')
    op.drop_index(op.f('ix_tiers_id'), table_name='tiers')
    op.drop_table('tiers')
    op.drop_index(op.f('ix_payments_provider_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_data_source_log_id'), table_name='data_source_log')
    op.drop_table('data_source_log')
    # ### end Alembic commands ###
