"""add trend and frequent score in insights table

Revision ID: d29cc056f565
Revises: 4870683592e2
Create Date: 2025-09-10 15:02:28.883719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29cc056f565'
down_revision: Union[str, None] = '4870683592e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('frequent_score', sa.DOUBLE_PRECISION(), nullable=False))
    op.add_column('insights', sa.Column('trend_score', sa.DOUBLE_PRECISION(), nullable=False))
    op.drop_column('insights', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('insights', 'trend_score')
    op.drop_column('insights', 'frequent_score')
    # ### end Alembic commands ###
