"""changed scoring system

Revision ID: df310a96dc82
Revises: 4e3b0e36f62b
Create Date: 2025-10-02 15:21:36.766390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df310a96dc82'
down_revision: Union[str, None] = '4e3b0e36f62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('relevancy_score', sa.DOUBLE_PRECISION(), nullable=False))
    op.add_column('insights', sa.Column('consistency_score', sa.DOUBLE_PRECISION(), nullable=False))
    op.drop_column('insights', 'trend_score')
    op.drop_column('insights', 'emerging_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('emerging_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('insights', sa.Column('trend_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('insights', 'consistency_score')
    op.drop_column('insights', 'relevancy_score')
    # ### end Alembic commands ###
