"""composite unique things in insights table

Revision ID: efdee5ad23ae
Revises: 020582b76962
Create Date: 2025-09-13 14:37:09.714474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdee5ad23ae'
down_revision: Union[str, None] = '020582b76962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_topic_per_dataset', 'insights', ['dataset_id', 'topic'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_topic_per_dataset', 'insights', type_='unique')
    # ### end Alembic commands ###
