name: Test, build docker-image, and push to GHCR

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull LFS files
        run: git lfs pull

      - name: Set up python 3.12.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest on tests dir
        run: |
          pip install pytest pytest-cov
          pytest tests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/amd64 \
            -t ghcr.io/${{ github.repository_owner }}/reas-backend:latest \
            -f .Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/reas-backend:latest
